# -*- coding: utf-8 -*-
"""Project_N.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ene3FDXKIBEj7PQ7M1cKq0hFubduK3A8
"""

import torch
import torch.nn as nn
import math
import argparse
import pickle
import sys
from pathlib import Path
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import shutil
import os




"""### Custom Tabular Input Embedding

Since our input data is tabular with mixed categorical and numerical features, we need a custom input embedding layer. This layer will:

1.  Map `trans_hour` to an embedding.
2.  Map `category` to an embedding.
3.  Apply a linear projection to `amt_log` (numerical) to convert it into an embedding of the same `d_model` size.
4.  Combine these three embeddings into a sequence, which will then be passed to the Transformer's positional encoding and encoder blocks.

This approach effectively treats each feature as a 'token' in the input sequence for the Transformer.
"""

class TabularInputEmbedding(nn.Module):
    def __init__(self, d_model: int, hour_vocab_size: int, category_vocab_size: int):
        super().__init__()
        self.d_model = d_model

        # Embedding for 'trans_hour'
        self.hour_embedding = nn.Embedding(hour_vocab_size, d_model)

        # Embedding for 'category'
        self.category_embedding = nn.Embedding(category_vocab_size, d_model)

        # Linear projection for 'amt_log' (numerical feature)
        self.amt_log_projection = nn.Linear(1, d_model)

    def forward(self, trans_hour_idx, category_idx, amt_log_val):
        # Ensure inputs to embeddings are LongTensor
        hour_embed = self.hour_embedding(trans_hour_idx.long()) * math.sqrt(self.d_model)
        cat_embed = self.category_embedding(category_idx.long()) * math.sqrt(self.d_model)

        # amt_log_val is a float, unsqueeze to add feature dimension for linear layer
        amt_embed = self.amt_log_projection(amt_log_val.unsqueeze(-1)) * math.sqrt(self.d_model)

        # Concatenate embeddings along the sequence dimension (dim=1) to form a sequence of tokens
        # Each feature becomes a token in the sequence.
        # Input shape: (batch_size), Output shape of each embed: (batch_size, d_model)
        # Stack to get (batch_size, num_features, d_model)
        return torch.stack([hour_embed, cat_embed, amt_embed], dim=1)
    
class PostionalEncoding(nn.Module):
  def __init__(self, d_model, max_len:int,dropout:float)->None:
    super().__init__() # Added super().__init__()
    self.d_model=d_model
    self.max_len=max_len
    self.dropout=nn.Dropout(dropout) # Moved dropout initialization here
    pe=torch.zeros(max_len,d_model)
    position=torch.arange(0,max_len,dtype=torch.float).unsqueeze(1)
    div_term=torch.exp(torch.arange(0,d_model,2).float()*(-math.log(10000.0)/d_model))
    pe[:,0::2] = torch.sin(position*div_term)
    pe[:,1::2] = torch.cos(position*div_term)
    pe=pe.unsqueeze(0)
    self.register_buffer('pe',pe) # Fixed typo: regiter_buffer to register_buffer
  def forward(self,x):
    x=x+(self.pe[:,:x.shape[1]]).requires_grad_(False)
    return self.dropout(x)

class MultiHeadAttentionBlock(nn.Module):
  def __init__(self,d_model:int, h:int, dropout:float)->None:
    super().__init__() # Added super().__init__()
    self.d_model=d_model
    self.h=h
    assert d_model % h == 0, "d_model is not divisible by h"
    #ensure the d_model is divisible number of head
    self.d_k=d_model//h
    self.w_q=nn.Linear(d_model,d_model,bias=False) #query
    self.w_k=nn.Linear(d_model,d_model,bias=False) #key
    self.w_v=nn.Linear(d_model,d_model,bias=False) #weight
    self.w_o=nn.Linear(d_model,d_model,bias=False) #output
    self.dropout=nn.Dropout(dropout)

  @staticmethod
  def attention(query,key,value,mask,dropout:nn.Dropout):
    d_k=query.shape[-1]
    # gets dimension of keys/queries.
    attention_scores=torch.matmul(query,key.transpose(-2,-1))/math.sqrt(d_k)
    if mask is not None:
      attention_scores=attention_scores.masked_fill(mask==0,-1e9)
    attention_scores=torch.softmax(attention_scores,dim=-1)
    if dropout is not None:
      attention_scores=dropout(attention_scores)
    return torch.matmul(attention_scores, value), attention_scores # Corrected return value

  def forward(self,q,k,v,mask):
    query = self.w_q(q)
    key = self.w_k(k)
    value = self.w_v(v)

    query = query.view(query.shape[0],query.shape[1],self.h,self.d_k).transpose(1,2)
    key = key.view(key.shape[0],key.shape[1],self.h,self.d_k).transpose(1,2)
    value = value.view(value.shape[0],value.shape[1],self.h,self.d_k).transpose(1,2)

    x,self.attention_scores=MultiHeadAttentionBlock.attention(query,key,value,mask,self.dropout)
    x=x.transpose(1,2).contiguous().view(x.shape[0], -1, self.h * self.d_k) # Corrected view call
    return self.w_o(x)

class LayerNormalization(nn.Module):
  def __init__(self,feature:int , eps:float=10**-6) ->None:
    super().__init__()
    self.eps=eps
    self.alpha = nn.Parameter(torch.ones(feature))
    self.bias = nn.Parameter(torch.zeros(feature))

  def forward(self,x):
    mean=x.mean(-1,keepdim=True)
    std=x.std(-1,keepdim=True)
    return self.alpha * (x-mean)/(std+self.eps) + self.bias

class FeedForwardBlock(nn.Module):
    def __init__(self, d_model: int, d_ff: int, dropout: float) -> None:
        super().__init__()
        self.linear_1 = nn.Linear(d_model, d_ff)
        self.dropout = nn.Dropout(dropout)
        self.linear_2 = nn.Linear(d_ff, d_model)

    def forward(self, x):
        return self.linear_2(self.dropout(torch.relu(self.linear_1(x))))

class ResidualConnection(nn.Module):
  def __init__(self,feature:int,dropout:float)->None:
    super().__init__()
    self.dropout=nn.Dropout(dropout)
    self.norm=LayerNormalization(feature)

  def forward(self,x,sublayer):
    return x+self.dropout(sublayer(self.norm(x)))

class EncoderBlock(nn.Module):
  def __init__(self, features: int, self_attention_block: MultiHeadAttentionBlock, feed_forward_block: FeedForwardBlock, dropout: float) -> None:
    super().__init__() # Added super().__init__()
    self.self_attention_block = self_attention_block
    self.feed_forward_block = feed_forward_block
    self.residual_connections = nn.ModuleList([ResidualConnection(features,dropout) for _ in range(2)])
  def forward(self, x, src_mask):
    x = self.residual_connections[0](x,lambda x: self.self_attention_block(x,x,x,src_mask))
    x = self.residual_connections[1](x, self.feed_forward_block)
    return x

class Encoder(nn.Module):
    # Removed vocab_size and max_len, as the Encoder now expects already embedded inputs
    def __init__(self, d_model: int, N: int, h: int, dropout: float) -> None:
        super().__init__()
        self.d_model = d_model
        self.N = N
        # Removed redundant InputEmbeding and PostionalEncoding initialization
        self.layers = nn.ModuleList([
            EncoderBlock(d_model,
                         MultiHeadAttentionBlock(d_model, h, dropout),
                         FeedForwardBlock(d_model, 4 * d_model, dropout),
                         dropout)
            for _ in range(N)
        ])
        self.norm = LayerNormalization(d_model)

    def forward(self, x, src_mask):
        # x is assumed to be already embedded and positionally encoded
        for layer in self.layers:
            x = layer(x, src_mask)
        return self.norm(x)



"""### Transformer Classifier Model

Now, we'll build a `TransformerClassifier` which will utilize the `Encoder` part of the Transformer architecture for our fraud detection task. This model will:

1.  Take the raw tabular features as input.
2.  Pass them through our `TabularInputEmbedding` to get a sequence of embeddings.
3.  Add positional encoding using `PostionalEncoding`.
4.  Feed the embedded sequence into the `Encoder`.
5.  Apply a pooling strategy (e.g., mean pooling over the sequence dimension) to get a fixed-size representation of the entire input transaction.
6.  Pass this pooled representation through a final linear layer to output classification logits (for `is_fraud`).
"""

class TransformerClassifier(nn.Module):
    def __init__(
        self,
        tabular_embed: TabularInputEmbedding,
        positional_encoding: PostionalEncoding,
        encoder: Encoder,
        num_classes: int = 2, # Binary classification for fraud detection
        dropout: float = 0.1
    ) -> None:
        super().__init__()
        self.tabular_embed = tabular_embed
        self.positional_encoding = positional_encoding
        self.encoder = encoder

        # Classification head
        self.classifier = nn.Sequential(
            nn.Linear(encoder.d_model, encoder.d_model // 2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(encoder.d_model // 2, num_classes)
        )

    def forward(self, trans_hour_idx, category_idx, amt_log_val, src_mask=None):
        # Get embeddings from tabular data
        # Shape: (batch_size, max_seq_len, d_model)
        x = self.tabular_embed(trans_hour_idx, category_idx, amt_log_val)

        # Add positional encoding
        x = self.positional_encoding(x)

        # Pass through the encoder
        # src_mask is generally not needed for fixed-length tabular input unless there's padding
        encoder_output = self.encoder(x, src_mask)

        # Pooling strategy: Mean pooling over the sequence dimension
        # From (batch_size, max_seq_len, d_model) to (batch_size, d_model)
        pooled_output = encoder_output.mean(dim=1)

        # Pass through the classification head
        logits = self.classifier(pooled_output)

        return logits

from torch.utils.data import Dataset, DataLoader

# --- 1. Build the Transformer Classifier Model ---
def build_transformer_classifier(
    d_model: int,
    max_seq_len: int,
    hour_vocab_size: int,
    category_vocab_size: int,
    N: int, # Number of encoder layers
    h: int, # Number of attention heads
    dropout: float,
    num_classes: int = 2
) -> TransformerClassifier:

    # Input Embedding layer
    tabular_embed = TabularInputEmbedding(
        d_model=d_model,
        hour_vocab_size=hour_vocab_size,
        category_vocab_size=category_vocab_size
    )

    # Positional Encoding layer
    pos_encoding = PostionalEncoding(d_model, max_seq_len, dropout)

    # Encoder part
    encoder = Encoder(
        d_model=d_model,
        N=N,
        h=h,
        dropout=dropout
    )

    # Transformer Classifier
    model = TransformerClassifier(
        tabular_embed=tabular_embed,
        positional_encoding=pos_encoding,
        encoder=encoder,
        num_classes=num_classes,
        dropout=dropout
    )
    return model

